kind: Deployment
apiVersion: apps/v1
metadata:
  name: tritonnfs-csi-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tritonnfs-csi-controller
  template:
    metadata:
      labels:
        app: tritonnfs-csi-controller
    spec:
      serviceAccount: tritonnfs-csi-controller-sa
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--feature-gates=Topology=true"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.3.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.8.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: tritonnfs-csi-plugin
          image: nwilkens/tritonnfs-csi:v0.6.0
          imagePullPolicy: IfNotPresent
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--driver-name=tritonnfs.csi.triton.com"
            - "--node-id=$(NODE_ID)"
            - "--cloud-api=$(TRITON_CLOUDAPI)"
            - "--account-id=$(TRITON_ACCOUNT_ID)"
            - "--key-id=$(TRITON_KEY_ID)" 
            - "--key-path=/etc/triton/key.pem"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TRITON_CLOUDAPI
              valueFrom:
                secretKeyRef:
                  name: triton-creds
                  key: cloudapi
            - name: TRITON_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: triton-creds
                  key: account-id
            - name: TRITON_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: triton-creds
                  key: key-id
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            - name: triton-key
              mountPath: /etc/triton
              readOnly: true
          securityContext:
            privileged: true
            runAsUser: 0
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: triton-key
          secret:
            secretName: triton-creds
            items:
              - key: key.pem
                path: key.pem
                mode: 0600