kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: tritonnfs-csi-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: tritonnfs-csi-node
  template:
    metadata:
      labels:
        app: tritonnfs-csi-node
    spec:
      serviceAccount: tritonnfs-csi-node-sa
      hostNetwork: true
      containers:
        - name: node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
            - "--v=5"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/tritonnfs.csi.triton.com /registration/tritonnfs.csi.triton.com-reg.sock"]
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/tritonnfs.csi.triton.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: tritonnfs-csi-plugin
          image: nwilkens/tritonnfs-csi:v0.4.3
          imagePullPolicy: IfNotPresent
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--driver-name=tritonnfs.csi.triton.com"
            - "--node-id=$(NODE_ID)"
            - "--cloud-api=$(TRITON_CLOUDAPI)"
            - "--account-id=$(TRITON_ACCOUNT_ID)"
            - "--key-id=$(TRITON_KEY_ID)" 
            - "--key-path=/etc/triton/key.pem"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TRITON_CLOUDAPI
              valueFrom:
                secretKeyRef:
                  name: triton-creds
                  key: cloudapi
            - name: TRITON_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: triton-creds
                  key: account-id
            - name: TRITON_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: triton-creds
                  key: key-id
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: triton-key
              mountPath: /etc/triton
              readOnly: true
            - name: device-dir
              mountPath: /dev
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/tritonnfs.csi.triton.com
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
        - name: triton-key
          secret:
            secretName: triton-creds
            items:
              - key: key.pem
                path: key.pem
                mode: 0600