apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: tritonnfs.csi.triton.com
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
  fsGroupPolicy: File